### ISSUE TITLE
Readme Enhancement

### ISSUE THREAD

**Issue by SrijanShovit** [SrijanShovit/carbonops-v2#28]
The thanks for visiting if moves from right to left in the readme bottom or any nice animation would be amazing!!

**Comment by MahendraDani** [comment]
@SrijanShovit Would you please elaborate what is the expected outcome for this issue. I would like to work on this issue.
Thanks!

**Comment by shreya024** [comment]
> @SrijanShovit Would you please elaborate what is the expected outcome for this issue. I would like to work on this issue. Thanks!

@MahendraDani Add some nice animation to make "Thanks for visiting" move from left to right in the README.md file

**Comment by MahendraDani** [comment]
@shreya024 Alright! Will work on it!
Thanks!

**Comment by MahendraDani** [comment]
@shreya024 @SrijanShovit 
I tried to create a animation in README.md file but it is not working!
To create animations in markdown files we need to use html and css particularly `@keyframes` in css. But markdown files only allow inline css. So only **inline css** can be added to the html elements. And `@keyframes` properties do not work as **inline css**.

So should I add a gif instead of animations? 
Please provide your input!
Thanks.

**Comment by shreya024** [comment]
> @shreya024 @SrijanShovit I tried to create a animation in README.md file but it is not working! To create animations in markdown files we need to use html and css particularly `@keyframes` in css. But markdown files only allow inline css. So only **inline css** can be added to the html elements. And `@keyframes` properties do not work as **inline css**.
> 
> So should I add a gif instead of animations? Please provide your input! Thanks.

I think GIF will be fine, @SrijanShovit ?

**Comment by MahendraDani** [comment]
@SrijanShovit @shreya024 So should I add *thank you* gif in the `README.md` file?
