### ISSUE TITLE
About Us UI Implementation

### ISSUE THREAD

**Issue by shreya024** [SrijanShovit/carbonops-v2#30]
## Description:
- Implement About Us UI using NextUI or Material UI (mui) and Tailwind CSS according to the following design
- On Clicking the About Us button on HomePage,this page will open
- Make sure that the UI is fully responsive

## Design:
![about-us](https://github.com/SrijanShovit/carbonops-v2/assets/72400676/4841c912-d0d6-497b-be07-4885a4adaec4)

**Comment by khushi1711** [comment]
i would like to work on this.assign it to me

**Comment by shreya024** [comment]
> i would like to work on this.assign it to me

@khushi1711 Assigned.Go ahead!

**Comment by Anshika-Jain02** [comment]
@khushi1711 are you working on the the responsiveness of "About us " section? As I am currently working on the UI of cards in the about us section according to #24 and your issue is to solve the responsiveness issue of the same. so, I think it would be better if you wait until my additions are merged so, that you can make them responsive accordingly.

**Comment by shreya024** [comment]
> > i would like to work on this.assign it to me
> 
> @khushi1711 Assigned.Go ahead!

Any updates @khushi1711 ?

**Comment by Hemant2335** [comment]
If noone is working on this please assign it to me under Gssoc'23

Thank you

**Comment by shreya024** [comment]
> If noone is working on this please assign it to me under Gssoc'23
> 
> Thank you

@Hemant2335 Go ahead!

**Comment by Hemant2335** [comment]
ok I am on it .
